### ISSUE TITLE
How does this compare to- or work with BulletUpHell?

### ISSUE THREAD

**Issue by temhotaokeaha** [Moonzel/Godot-PerfBullets#3]
Just to be clear, this is not a dig at either plugin, I'm simply curious about your thoughts. If I'm getting it right, PerfBullets is more focused on performance (duh), while BulletUpHell is focused on general ease of development. 

Since both are about the same game genre, maybe there are plans for some integration/"cross-reference"?

(link to the plugin I'm referring to: https://github.com/Dark-Peace/BulletUpHell)

(edit) opened "cross-issue" there: https://github.com/Dark-Peace/BulletUpHell/issues/5

**Comment by Moonzel** [comment]
I am familiar with the plugin! I worked with Dark Peace (the developer) to improve his plugin before I started work on PerfBullets. I agree, his plugin is more user-friendly, but when I used his plugin, it was not performant enough to run stablely on my computer. That is why I started with PerfBullets in the first place. My plugin uses niche parts of Godot such as the MultiMeshInstance2D to make the most permanent drawing, but that does come with drawbacks. It is harder to add more properties and features because of that and because the plugin is written mostly in C++. In the future, I am open to a collaboration to combine our plugins, but at the moment, nothing is planned. If you would like, you could reach out to Dark Peace via his discord (mentioned in the README of his plugin), and ask if he would be willing to do that. I will leave this issue open in case you want to follow-up. Thanks for the question and good luck developing!

**Comment by Moonzel** [comment]
I am open to future collaboration, but Dark Peace has shown signs of being too busy. If anyone were to want to assist with this in the future it may happen, but it is not at the moment.
